on:
  issues:
    types: [labeled]
  workflow_dispatch:
jobs:
  updateRepos:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリの環境を仮想環境に作成（CheckOut）
        uses: actions/checkout@v3
      - name: DEBUG
        env:
          DEBUG: ${{ toJson(github.event) }}
        run: echo "$DEBUG"
      - name: Hugoの記法に合わせてファイルを生成（Generate Post）
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
          POST_ID: ${{ github.event.issue.id }}
          POST_CATEGORY: ${{ github.event.issue.labels[0].name }}
        run: |
           YEAR=`date "+%Y"`
           MONTH=`date "+%m"`
           mkdir -p content/posts/$YEAR/$MONTH
           cd content/posts/$YEAR/$MONTH
           cat > $POST_ID.md <<EOF
           ---
           draft: false
           title: $POST_TITLE
           date: ${{ github.event.issue.updated_at }}
           type: post
           slug: $POST_ID
           category: ["${POST_CATEGORY}"]
           ---

           $POST_BODY
               
      - name: テスト
        run: |
          pwd
          ls -la
 #     - name: push
 #       env: 
 #         EMAIL: ${{secrets.EMAIL}}
 #       run: |
 #          date > genereate.txt
 #          git config user.name scrymee
 #          git config user.email "$EMAIL"
 #          git add .
 #          git commit -m 'test'
 #           git push
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
        
