on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: checkDirectry
        run: |
          pwd
          ls -la
          echo 'hello world' > hello.md
          ls -la
      - name: push
        env: 
          EMAIL: ${{secrets.EMAIL}}
        run: |
           date > genereate.txt
           git config user.name scrymee
           git config user.email "$EMAIL"
           git add .
           git commit -m 'test'
            git push
        
        
