on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > genereate.txt
          git config user.name scrymee
          git config user.email syoumee@gmail.com
          git add .
          git commit -m 'test'
          git push
        
        
