on:
  issues:
    types: [labeled]
  workflow_dispatch:
jobs:
  updateRepos:
    runs-on: ubuntu-latest
    steps:
      - name: checkOutMyrepository
        uses: actions/checkout@v3
      - name: テスト
        run: |
          pwd
          ls -la
          echo 'hello world' > hello.md
          echo "${{github.event.label.name}}"
          echo '${{ toJSON(github.event) }}'
          ls -la
      - name: push
        env: 
          EMAIL: ${{secrets.EMAIL}}
        run: |
           date > genereate.txt
           git config user.name scrymee
           git config user.email "$EMAIL"
           git add .
           git commit -m 'test'
            git push
        
        
