name: Issue Label Trigger
on:
  issues:
    types: [edited]

jobs:
  check_issue_label:
    runs-on: ubuntu-latest
    steps:
    - name: Check issue label
      env:
        EVENT: ${{ toJson(github.event) }}
      run: |
        echo "$EVENT"
        echo '--------------------------------------'
        echo  "${{ github.event.issue.labels }}"
        echo '--------------------------------------'
        echo  "${{ github.event.issue.labels }}" | grep 'publish'
        echo "====================================="        
        if echo "${{ github.event.issue.labels }}" | grep -q 'publish'; then
          echo "Issue has 'publish' label. Do something!"
        else
          echo "Issue does not have 'publish' label. Skipping."
        fi
