name: Issue Label Trigger
on:
  issues:
    types: [edited]

jobs:
  check_issue_label:
    runs-on: ubuntu-latest
    steps:
    - name: Check issue label
      env:
        EVENT: ${{ toJson(github.event) }}
      run: |
        echo "$EVENT"
        if echo "${{ github.event.issue.labels }}" | grep -q 'name: publish'; then
          echo "Issue has 'publish' label. Do something!"
        else
          echo "Issue does not have 'publish' label. Skipping."
        fi

    - name: Check issue label
      run: |
        # ここに実行したいコマンドを記述します
        echo "Issue has 'publish' label. Do something!"
