name: Issue Label Trigger
on:
  issues:
    types: [edited]

jobs:
  check_issue_label:
    runs-on: ubuntu-latest
    steps:
    - name: 作成テスト
      env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
          POST_ID: ${{ github.event.issue.id }}
          POST_CATEGORY: ${{ toJSon(github.event.issue.labels.*.name) }}
      run: |
          POST_CATEGORY=${POST_CATEGORY#[}
          POST_CATEGORY=${POST_CATEGORY%]}
          POST_CATEGORY_ARRAY=(POST_CATEGORY)
          TAGS=''
          for v in ${POST_CATEGORY_ARRAY[@]}
          do
            TAGS=$TAGS","$v
            echo $TAGS
          done
           YEAR=`date "+%Y"`
           MONTH=`date "+%m"`
           mkdir -p content/posts/$YEAR/$MONTH
           touch content/posts/$YEAR/_index.md
           touch content/posts/$YEAR/$MONTH/_index.md
           cd content/posts/$YEAR/$MONTH
           cat > $POST_ID.md <<EOF
           ---
           draft: false
           title: $POST_TITLE
           date: ${{ github.event.issue.updated_at }}
           slug: $POST_ID
           category: ["test"]
           thumbnailImagePosition: "top"
           thumbnailImage: //d1u9biwaxjngwg.cloudfront.net/welcome-to-tranquilpeak/city-750.jpg
           coverImage: //d1u9biwaxjngwg.cloudfront.net/welcome-to-tranquilpeak/city.jpg
           metaAlignment: center
           ---
           「$POST_TITLE」に関しての考えをまとめました。
           <!--more-->
           
           {{< toc >}}

           $POST_BODY
           EOF
    - name: checkPostData
      env: 
        POST_ID: ${{ github.event.issue.id }}
      run: |
           cat ${POST_ID}.md
    - name: Check issue label
      if: ${{ github.event.action == 'labeled'}}
      env:
        EVENT: ${{ toJson(github.event) }}
        LABELS: ${{ toJson(github.event.issue.labels) }}
        NAMES: ${{ toJson(github.event.issue.labels.*.name) }}
      run: |
        echo "$EVENT"
        echo '--------------------------------------'
        echo  "$NAMES"
        echo '--------------------------------------'
        echo 'Lavel'
        echo '--------------------------------------'
        echo "${LABELS}"
        echo '--------------------------------------'
        echo 'loop'
        echo '--------------------------------------'
        NAMES=${NAMES#[}
        NAMES=${NAMES%]}
        NAMES_ARRAY=(NAMES)
        for v in ${NAMES[@]}
          do
          echo "$v"
          echo 'loop count'
        done
        echo "====================================="        
        if echo "${NAMES}" | grep -q 'publish'; then
          echo "Issue has 'publish' label. Do something!"
        else
          echo "Issue does not have 'publish' label. Skipping."
        fi
    - name: chek2
      if: contains(github.event.issue.labels.*.name, 'publish')
      run: |
        echo 'labelCheck clear'

